language: python
sudo: required
python:
  - "3.6"
install:
  - pip intstall -r requirements.txt
  - sudo curl --proto '=https' --tlsv1.2 -sSf -y https://sh.rustup.rs | sh
  - cd rust_reject && cargo build --release
  - cd ..
script:
  - python evaluation.py
